import path from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
dotenv.config({ path: path.resolve(__dirname, "../../../.env") });

import { getDb, schema } from "@klinpi/db";

type Db = ReturnType<typeof getDb>;

/* ------------------------------------------------------------------ *
 * Dev fixtures — IDs are generated by the schema (crypto.randomUUID)
 * ------------------------------------------------------------------ */

const DEV_USER = {
  email: "arav@klinpi.dev",
  name: "Arav Menon",
  password: "klinpi123",
  passwordHash:
    "$2b$12$HItCnuXKAGXYXBXA9Pma1OshTCTnSyyjo3lvar8kMKQENVPkh.t3m",
};

const DEV_REPOSITORY = {
  provider: "GITHUB" as const,
  providerRepoId: "777000001",
  owner: "Arav-Menon",
  name: "py-baackend",
  fullName: "Arav-Menon/py-baackend",
  cloneUrl: "https://github.com/Arav-Menon/py-baackend.git",
  defaultBranch: "main",
};

interface SeedMessage {
  role: "USER" | "ASSISTANT";
  content: string;
  ageMinutes: number;
}

interface SeedSession {
  title: string;
  status: "ACTIVE" | "ARCHIVED";
  linkedToRepository: boolean;
  updatedMinutesAgo: number;
  messages: SeedMessage[];
}

const SEED_SESSIONS: SeedSession[] = [
  {
    title: "Fix login redirect loop",
    status: "ACTIVE",
    linkedToRepository: true,
    updatedMinutesAgo: 12,
    messages: [
      {
        role: "USER",
        ageMinutes: 47,
        content:
          "After signing in I get bounced back to /login. The session cookie looks fine. Can you investigate?",
      },
      {
        role: "ASSISTANT",
        ageMinutes: 45,
        content:
          "The auth callback sets the cookie with `path: /login`, so the browser drops it on every request to `/`. I will move the cookie path to `/` in `lib/jwt.ts` and re-test.",
      },
      {
        role: "USER",
        ageMinutes: 32,
        content: "Great — apply the fix and add a regression test.",
      },
      {
        role: "ASSISTANT",
        ageMinutes: 30,
        content:
          "Fixed `setAuthCookie` to use `path: /` and added a test covering the post-login redirect. The loop is gone.",
      },
    ],
  },
  {
    title: "Add rate limiting to API routes",
    status: "ACTIVE",
    linkedToRepository: true,
    updatedMinutesAgo: 180,
    messages: [
      {
        role: "USER",
        ageMinutes: 200,
        content:
          "Auth endpoints are getting hammered. Add rate limiting to the sign-in and sign-up routes.",
      },
      {
        role: "ASSISTANT",
        ageMinutes: 195,
        content:
          "Added a 10 requests / 10 minute limiter backed by Redis (`authLimit`) and applied it to `/api/v1/auth/*`. Excess requests now get 429.",
      },
    ],
  },
  {
    title: "Write onboarding README",
    status: "ARCHIVED",
    linkedToRepository: true,
    updatedMinutesAgo: 2880,
    messages: [
      {
        role: "USER",
        ageMinutes: 2900,
        content:
          "Draft a README section explaining local setup: Postgres, Redis, Ollama and the seed command.",
      },
      {
        role: "ASSISTANT",
        ageMinutes: 2885,
        content:
          "Added a 'Local development' section covering the docker services, `pnpm drizzle:migrate`, `pnpm --filter @klinpi/runtime seed`, and starting the gRPC runtime on :50051.",
      },
    ],
  },
  {
    title: "How does deployment work?",
    status: "ACTIVE",
    linkedToRepository: false,
    updatedMinutesAgo: 1440,
    messages: [
      {
        role: "USER",
        ageMinutes: 1500,
        content: "How do we deploy this project to production?",
      },
      {
        role: "ASSISTANT",
        ageMinutes: 1495,
        content:
          "Gateway and Studio run as Node services behind a reverse proxy, the runtime gRPC service stays on the internal network, and Postgres/Redis are managed services. Migrations run as a release step with `pnpm drizzle:migrate`.",
      },
    ],
  },
];

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */

const minutesAgo = (minutes: number): Date =>
  new Date(Date.now() - minutes * 60_000);

const TABLES_IN_DELETE_ORDER = [
  schema.approvals,
  schema.toolCalls,
  schema.sandboxes,
  schema.agentRuns,
  schema.messages,
  schema.memories,
  schema.agentSessions,
  schema.repositories,
  schema.oauthAccounts,
  schema.users,
];

async function resetDatabase(db: Db): Promise<void> {
  for (const table of TABLES_IN_DELETE_ORDER) {
    await db.delete(table);
  }
  console.log("Database reset: all tables emptied.");
}

async function seedUser(db: Db): Promise<string> {
  const [user] = await db
    .insert(schema.users)
    .values({
      email: DEV_USER.email,
      name: DEV_USER.name,
      passwordHash: DEV_USER.passwordHash,
    })
    .returning();

  if (!user) throw new Error("Failed to create dev user");
  return user.id;
}

async function seedRepository(db: Db, userId: string): Promise<string> {
  const [repository] = await db
    .insert(schema.repositories)
    .values({ ...DEV_REPOSITORY, userId })
    .returning();

  if (!repository) throw new Error("Failed to create dev repository");
  return repository.id;
}

async function seedSessions(
  db: Db,
  userId: string,
  repositoryId: string,
): Promise<Array<{ id: string; title: string; status: string; messageCount: number }>> {
  const created: Array<{
    id: string;
    title: string;
    status: string;
    messageCount: number;
  }> = [];

  for (const session of SEED_SESSIONS) {
    const updatedAt = minutesAgo(session.updatedMinutesAgo);
    const oldestMessageAge = session.messages.reduce(
      (max, message) => Math.max(max, message.ageMinutes),
      session.updatedMinutesAgo,
    );

    const [row] = await db
      .insert(schema.agentSessions)
      .values({
        userId,
        repositoryId: session.linkedToRepository ? repositoryId : null,
        title: session.title,
        status: session.status,
        createdAt: minutesAgo(oldestMessageAge),
        updatedAt,
      })
      .returning();

    if (!row) throw new Error(`Failed to create session "${session.title}"`);

    if (session.messages.length > 0) {
      await db.insert(schema.messages).values(
        session.messages.map((message) => ({
          sessionId: row.id,
          role: message.role,
          content: message.content,
          metadata: null,
          createdAt: minutesAgo(message.ageMinutes),
        })),
      );
    }

    created.push({
      id: row.id,
      title: session.title,
      status: session.status,
      messageCount: session.messages.length,
    });
  }

  return created;
}

/* ------------------------------------------------------------------ *
 * Main
 * ------------------------------------------------------------------ */

async function main(): Promise<void> {
  const db = getDb();

  await resetDatabase(db);

  const userId = await seedUser(db);
  const repositoryId = await seedRepository(db, userId);
  const sessions = await seedSessions(db, userId, repositoryId);

  const separator = "─".repeat(72);
  const totalMessages = sessions.reduce((sum, s) => sum + s.messageCount, 0);

  console.log(`\n${separator}`);
  console.log(" Klinpi seed complete");
  console.log(separator);
  console.log(` User       ${DEV_USER.email}`);
  console.log(`            password: ${DEV_USER.password}`);
  console.log(`            id: ${userId}`);
  console.log(` Repository ${DEV_REPOSITORY.fullName}`);
  console.log(`            cloneUrl: ${DEV_REPOSITORY.cloneUrl}`);
  console.log(`            id: ${repositoryId}`);
  console.log(` Sessions   ${sessions.length} created`);
  for (const session of sessions) {
    console.log(
      `            [${session.status.padEnd(8)}] ${session.title}`,
    );
    console.log(`                        id: ${session.id} (${session.messageCount} messages)`);
  }
  console.log(` Messages   ${totalMessages} created`);
  console.log(separator);

  const primary = sessions[0]!;
  console.log("\nExample gRPC / Postman body:\n");
  console.log(
    JSON.stringify(
      {
        sessionId: primary.id,
        userId,
        prompt: "hello, how are you?",
        repositoryId,
      },
      null,
      2,
    ),
  );
  console.log("");

  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
